<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.CompanyName.ChengxiaoA</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <Platforms>AnyCPU;x86</Platforms>

    <!-- 签名配置 -->
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>chengxiao.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>chengxiao</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>chengxiao123</AndroidSigningKeyPass>
    <AndroidSigningStorePass>chengxiao123</AndroidSigningStorePass>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
    <!-- 包含字体资源到 Android 项目 -->
    <AndroidAsset Include="..\ChengxiaoA\Assets\Fonts\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChengxiaoA\ChengxiaoA.csproj">
      <DefineConstants>ANDROID</DefineConstants>
    </ProjectReference>
  </ItemGroup>
</Project>
